---
title: "Proposal"
subtitle: "When Economics and DS Intersect..."
author: (DIC) David, Isauro, and Katherine
editor: 
  markdown: 
    wrap: 72
---

## Title: AI Usage For US Companies

-   **Short Description of the Project:** With AI usage soaring in
    recent years, our way of life has drastically changed. For this
    project, we will observe how this surge has impacted businesses
    across the US.

-   **2-3 General Research Questions:**

    1.  How has company AI usage changed over time?

    2.  How does company AI usage vary by location, such as state or
        urban/rural status?

    3.  How might company AI usage vary by internal factors, such as
        company size and ownership?

-   **Reasons/Inspirations Behind this Project:** Our group is composed
    of Economics majors, so we want to do a project that is related to
    our field. Additionally, we want to focus on recently developing
    news in order to make our project as relevant as possible, which is
    how we landed on AI usage as our topic.

-   **One Potential Dataset:** Annual Business Survey (ABS) Data
    2017-2023

**Communication Plan:** We will communicate primarily through GChat, and
each team member will respond as soon as possible, with more leeway
given during holidays and weekends. We will set up meetings outside of
class on a needs-based basis, with all members having allocated
11am-12pm on Fridays for such meetings. More meetings may be scheduled
depending on the workload of a milestone.

**Roles:**

-   Primary Point of Contact: Katherine Manuel

-   Technical Lead: David Torres

-   Style Lead: Isauro Reyes

**Conflict Resolution SOP:** If a team member misses a deadline, the
other team members will reach out to them and determine how to proceed
(i.e. if they need extra help, if we as a team need to request an
extension, etc.). The matter will only be elevated to the professor if
absolutely necessary, which we do not anticipate. For evenly split
decisions where the team doesn’t know how to proceed, we will flip a
coin/decide randomly. However, we don’t expect this to be an issue since
there are 3 of us.

## Appendix

## Data Import

```{r}
us_census_data_api_key <- "ec034959242822ec7117a80c8bd3f7e40892791c"

base_url <- "https://api.census.gov"
file_path <- "data/2023/abscb"

request <- httr2::request(base_url) |> 
  httr2::req_url_path_append(file_path) |> 
  httr2::req_url_query(
    get = c("EMP", "PAYANN", "FIRMPDEMP"),
    `for` = "state:*",
    key = us_census_data_api_key,
    .multi = "comma"
  )

request


## perform request

response <- request |> 
  httr2::req_perform()

response

##
class(response)     # OO classification
typeof(response)    # internal data type
str(response)       # internal data structure

##
data <- response |> 
  httr2::resp_body_json(simplifyVector = TRUE) |> 
  janitor::row_to_names(1) |> 
  dplyr::as_data_frame() |> 
  dplyr::mutate(across(c(EMP, PAYANN, FIRMPDEMP), as.numeric))

data

##

data |> 
  dplyr::group_by(state) |> 
  dplyr::summarise(across(c(EMP, PAYANN, FIRMPDEMP), list(
    n = \(x) dplyr::n(),
    min = \(x) min(x, na.rm = TRUE),
    mean = \(x) mean(x, na.rm = TRUE),
    max = \(x) max(x, na.rm = TRUE)
  ))) |> 
  tidyr::pivot_longer(cols = -state) |> 
  tidyr::pivot_wider(names_from = state, values_from = value) |>
  dplyr::mutate(name = stringr::str_remove(name, ".*_")) |> 
  gt::gt(rowname_col = "name") |> 
  gt::tab_row_group(
    label = "EMP",
    rows = 1:4) |> 
  gt::tab_row_group(
    label = "PAYANN",
    rows = 5:8) |> 
  gt::tab_row_group(
    label = "FIRMPDEMP",
    rows = 9:12)
```
